#lang racket
(define (reverse-general L)
  (if (null? L)
      (quote "the list is empty")
  (quote "the list is not empty")
  )
)

(reverse-general '())
(reverse-general '(a b c))
(reverse-general '(a b ()))
(reverse-general '((a b c)))
(reverse-general '((a b c) (d e f)))
(reverse-general '(a (b c) ((d e) f) g))
(reverse-general '(1 (2 3) (4 (a (b (c d)))))) 